# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(651, 476)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        PlotWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/oil-barrel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PlotWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PlotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LayGraph = QtWidgets.QHBoxLayout()
        self.LayGraph.setObjectName("LayGraph")
        self.verticalLayout_2.addLayout(self.LayGraph)
        self.LayTools = QtWidgets.QGridLayout()
        self.LayTools.setObjectName("LayTools")
        self.verticalLayout_2.addLayout(self.LayTools)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)
        PlotWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PlotWindow)
        self.statusbar.setObjectName("statusbar")
        PlotWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlotWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "Plot Window"))
import resgui_rc
